import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "PRJ-001",
    name: "쇼핑몰 관리자 페이지 리뉴얼",
    category: "개발 · 프론트엔드",
    client: "삼성전자",
    status: "IN_PROGRESS",
    contractAmount: 5000000,
    registeredAt: "2026.07.25",
  },
  {
    id: "PRJ-002",
    name: "모바일 앱 백엔드 API 개발",
    category: "개발 · 백엔드",
    client: "카카오",
    status: "NEGOTIATING",
    contractAmount: 4500000,
    registeredAt: "2026.07.28",
  },
  {
    id: "PRJ-003",
    name: "AI 추천 시스템 구축",
    category: "AI·ML · ML 엔지니어",
    client: "네이버",
    status: "RECRUITING",
    contractAmount: 7300000,
    registeredAt: "2026.07.20",
  },
  {
    id: "PRJ-004",
    name: "데이터 파이프라인 구축",
    category: "데이터 · 데이터 엔지니어",
    client: "삼성전자",
    status: "COMPLETED",
    contractAmount: 4800000,
    registeredAt: "2026.05.15",
  },
  {
    id: "PRJ-005",
    name: "핀테크 대시보드 개발",
    category: "개발 · 풀스택",
    client: "카카오",
    status: "REGISTERED",
    contractAmount: 8300000,
    registeredAt: "2026.08.05",
  },
  {
    id: "PRJ-006",
    name: "ERP 시스템 연동",
    category: "개발 · 백엔드",
    client: "네이버",
    status: "CONTRACT_PENDING",
    contractAmount: 5000000,
    registeredAt: "2026.06.20",
  },
];
