"use client";
import { useEffect, useState } from "react";
import AdminPageHeader from "@/features/common/components/Header";
import { ErrorState } from "@/features/common/components/ErrorState";
import { LoadingState } from "@/features/common/components/Loading";
import { fetchSettlements, fetchSettlementSummary } from "@/features/settlements/api";
import SettlementFilter, { type SettlementFilterValue } from "@/features/settlements/components/SettlementFilter";
import SettlementRow from "@/features/settlements/components/SettlementRow";
import SettlementStatCard from "@/features/settlements/components/SettlementStatCard";
import type { SettlementListResponse, SettlementSummary } from "@/features/settlements/types";
const EMPTY: SettlementFilterValue = { keyword: "", fromDate: "", toDate: "" };
export default function AdminSettlementsPage() {
  const [summary, setSummary] = useState<SettlementSummary | null>(null); const [list, setList] = useState<SettlementListResponse | null>(null); const [input, setInput] = useState(EMPTY); const [filters, setFilters] = useState(EMPTY); const [page, setPage] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [dateError, setDateError] = useState<string>();
  useEffect(() => { let active = true; fetchSettlementSummary().then((v) => { if (active) setSummary(v); }).catch(() => { if (active) setError("정산 요약을 불러오지 못했습니다."); }); return () => { active = false; }; }, []);
  useEffect(() => { let active = true; fetchSettlements({ ...filters, keyword: filters.keyword?.trim(), page, size: 20 }).then((v) => { if (active) { setList(v); setError(undefined); } }).catch((e: unknown) => { if (active) setError(e instanceof Error ? e.message : "정산 목록을 불러오지 못했습니다."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [filters, page]);
  const search = () => { if (input.fromDate && input.toDate && input.fromDate > input.toDate) { setDateError("시작일은 종료일보다 늦을 수 없습니다."); return; } setDateError(undefined); setPage(0); setFilters(input); };
  const cards = summary ? [{ label: "총 수수료 수익", amount: summary.totalRevenue }, { label: `${summary.revenueMonth} 수익`, amount: summary.monthlyRevenue }, { label: "결제 예정 금액", amount: summary.pendingAmount, count: summary.pendingCount }, { label: "미납", amount: summary.overdueAmount, count: summary.overdueCount }, { label: "결제 실패", amount: summary.failedAmount, count: summary.failedCount }, { label: "위약금 수수료", amount: summary.penaltyPaidAmount, count: summary.penaltyPaidCount }] : [];
  return <div className="min-h-screen bg-[#f7f8fa] p-4 sm:p-6 xl:p-8"><AdminPageHeader title="거래·정산 관리" description="플랫폼의 모든 정산 내역을 조회합니다." date={new Intl.DateTimeFormat("ko-KR", { dateStyle: "long" }).format(new Date())}/>{summary ? <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{cards.map((c) => <SettlementStatCard key={c.label} {...c}/>)}</section> : <LoadingState message="정산 요약을 불러오는 중입니다." className="min-h-24"/>}<section className="mt-6 overflow-hidden rounded-xl border border-[#e2e8f0] bg-white"><SettlementFilter value={input} onChange={setInput} onSearch={search} onReset={() => { setInput(EMPTY); setFilters(EMPTY); setPage(0); }} error={dateError} disabled={loading}/>{loading ? <LoadingState className="min-h-64"/> : error ? <ErrorState title="정산 내역을 불러오지 못했습니다" description={error}/> : list?.content.length ? <><div className="overflow-x-auto"><div className="min-w-[1080px]"><div className="grid h-11 grid-cols-[115px_1.7fr_110px_120px_105px_70px_100px_95px_100px_100px_60px] items-center bg-[#f8fafc] px-3 text-[12px] font-semibold text-[#94a3b8]"><span>정산번호</span><span>프로젝트</span><span>회원</span><span>유형</span><span>기준금액</span><span>수수료율</span><span>수수료</span><span>상태</span><span>기한</span><span>완료일</span><span>상세</span></div>{list.content.map((s) => <SettlementRow key={s.settlementId} settlement={s}/>)}</div></div><div className="flex items-center justify-between px-5 py-4 text-[13px]"><span>총 {list.totalElements.toLocaleString("ko-KR")}건 · {list.page + 1}/{Math.max(list.totalPages, 1)} 페이지</span><div className="flex gap-2"><button disabled={list.first} onClick={() => setPage(page - 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">이전</button><button disabled={list.last} onClick={() => setPage(page + 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">다음</button></div></div></> : <div className="py-16 text-center text-[#64748b]">조건에 맞는 정산 내역이 없습니다.</div>}</section></div>;
}
