import type { Inquiry } from "./types";

export const inquiries: Inquiry[] = [
  {
    id: "QNA-20260805-0012",
    memberType: "CLIENT",
    title: "착수금 수수료 결제 문의",
    author: "오이랩",
    createdAt: "2026.08.05",
    status: "ANSWERED",
    answeredAt: "2026.08.06",
    email: "contact@oilab.kr",
    category: "결제·수수료",
    content: "착수금 수수료 결제 버튼이 활성화되지 않습니다. 프로젝트를 등록하고 AI 검수를 완료했는데도 결제가 진행되지 않아 문의드립니다.",
    answer: "안녕하세요. 페어링 고객지원팀입니다. 착수금 수수료 결제는 프로젝트 등록과 AI 검수 결과 확인 후 진행할 수 있습니다. 결제가 완료되면 프로젝트 상태가 모집 중으로 변경되고 프리랜서 추천이 시작됩니다. 결제 버튼이 활성화되지 않는 경우 프로젝트 검수 상태와 등록된 결제수단을 확인해 주세요.",
  },
  {
    id: "QNA-20260804-0011",
    memberType: "FREELANCER",
    title: "프리랜서 프로필 수정 내용이 반영되지 않아요",
    author: "김개발",
    createdAt: "2026.08.04",
    status: "WAITING",
    answeredAt: null,
    email: "devkim@example.com",
    category: "프로필",
    content: "프리랜서 프로필을 수정했는데 변경한 내용이 화면에 반영되지 않습니다. 확인 부탁드립니다.",
    answer: null,
  },
  {
    id: "QNA-20260802-0010",
    memberType: "CLIENT",
    title: "프로젝트 등록 파일 업로드 오류",
    author: "파이낸스온",
    createdAt: "2026.08.02",
    status: "ANSWERED",
    answeredAt: "2026.08.03",
    email: "support@financeon.kr",
    category: "프로젝트",
    content: "프로젝트 등록 과정에서 첨부 파일 업로드가 완료되지 않습니다.",
    answer: "안녕하세요. 페어링 고객지원팀입니다. 첨부할 수 있는 파일 형식과 용량을 확인한 뒤 다시 시도해 주세요.",
  },
  {
    id: "QNA-20260801-0009",
    memberType: "FREELANCER",
    title: "AI 대리인 협상 결렬 후 재협상 방법",
    author: "박서버",
    createdAt: "2026.08.01",
    status: "WAITING",
    answeredAt: null,
    email: "serverpark@example.com",
    category: "AI 대리인",
    content: "AI 대리인 협상이 결렬된 뒤 다시 협상을 진행하는 방법을 알고 싶습니다.",
    answer: null,
  },
];
