"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminApiError } from "@/features/auth/api";
import { ErrorState } from "@/features/common/components/ErrorState";
import AdminPageHeader from "@/features/common/components/Header";
import { LoadingState } from "@/features/common/components/Loading";
import { ConfirmModal } from "@/features/common/components/Modal";
import { fetchSiteReviews, fetchSiteReviewSummary, updateSiteReviewVisibility } from "@/features/reviews/api";
import RatingDistribution from "@/features/reviews/components/RatingDistribution";
import ReviewFilter, { type ReviewFilterValue } from "@/features/reviews/components/ReviewFilter";
import ReviewRow from "@/features/reviews/components/ReviewRow";
import ReviewStatCard from "@/features/reviews/components/ReviewStatCard";
import type { SiteReview, SiteReviewListResponse, SiteReviewSummary } from "@/features/reviews/types";

type PendingAction = { type: "visibility" | "promotion"; review: SiteReview } | null;
const EMPTY_FILTERS: ReviewFilterValue = { keyword: "" };

export default function AdminReviewsPage() {
  const [summary, setSummary] = useState<SiteReviewSummary | null>(null); const [list, setList] = useState<SiteReviewListResponse | null>(null); const [input, setInput] = useState(EMPTY_FILTERS); const [filters, setFilters] = useState(EMPTY_FILTERS); const [page, setPage] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [pending, setPending] = useState<PendingAction>(null); const [submitting, setSubmitting] = useState(false); const [actionError, setActionError] = useState<string>();
  const loadSummary = useCallback(() => fetchSiteReviewSummary().then(setSummary).catch(() => setError("리뷰 요약을 불러오지 못했습니다.")), []);
  useEffect(() => { let active = true; fetchSiteReviewSummary().then((v) => { if (active) setSummary(v); }).catch(() => { if (active) setError("리뷰 요약을 불러오지 못했습니다."); }); return () => { active = false; }; }, []);
  useEffect(() => { let active = true; fetchSiteReviews({ ...filters, keyword: filters.keyword?.trim(), page, size: 20 }).then((v) => { if (active) { setList(v); setError(undefined); } }).catch((e: unknown) => { if (active) setError(e instanceof Error ? e.message : "리뷰 목록을 불러오지 못했습니다."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [filters, page]);
  const confirm = async () => { if (!pending) return; const visibility = pending.type === "visibility" ? (pending.review.visibility === "PUBLIC" ? "PRIVATE" : "PUBLIC") : pending.review.visibility; const promoted = pending.type === "visibility" && visibility === "PRIVATE" ? false : pending.type === "promotion" ? !pending.review.promoted : pending.review.promoted; setSubmitting(true); setActionError(undefined); try { const updated = await updateSiteReviewVisibility(pending.review.siteReviewId, visibility, promoted); setList((current) => current ? { ...current, content: current.content.map((item) => item.siteReviewId === updated.siteReviewId ? updated : item) } : current); setPending(null); await loadSummary(); } catch (e) { const apiError = e instanceof AdminApiError ? e : null; setActionError(apiError ? `${apiError.message}${apiError.traceId ? ` (traceId: ${apiError.traceId})` : ""}` : "리뷰 설정을 변경하지 못했습니다."); } finally { setSubmitting(false); } };
  const stats = summary ? [{ label: "평균 별점", value: summary.ratingAverage.toFixed(1) }, { label: "전체 리뷰", value: summary.totalCount }, { label: "이번 달", value: summary.thisMonthCount }, { label: "홍보 활용", value: summary.promotedCount }, { label: "홍보 제외", value: summary.notPromotedCount }, { label: "공개", value: summary.publicCount }] : [];
  const ratings = summary ? [5,4,3,2,1].map((rating) => ({ rating, count: summary.scoreDistribution[String(rating) as "1"|"2"|"3"|"4"|"5"] })) : [];
  const actionLabel = pending?.type === "visibility" ? pending.review.visibility === "PUBLIC" ? "비공개로 변경" : "공개로 변경" : pending?.review.promoted ? "홍보 제외" : "홍보 활용";
  const search = () => { setLoading(true); setPage(0); setFilters(input); };
  const reset = () => { setLoading(true); setInput(EMPTY_FILTERS); setFilters(EMPTY_FILTERS); setPage(0); };
  const changePage = (nextPage: number) => { setLoading(true); setPage(nextPage); };
  return <div className="min-h-screen bg-[#f7f8fa] p-4 sm:p-6 xl:p-8"><AdminPageHeader title="사이트 리뷰 관리" description="사이트 리뷰의 공개 및 홍보 활용 여부를 관리합니다." date={new Intl.DateTimeFormat("ko-KR", { dateStyle: "long" }).format(new Date())}/>{summary ? <><section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{stats.map((s) => <ReviewStatCard key={s.label} {...s}/>)}</section><RatingDistribution ratings={ratings}/></> : <LoadingState message="리뷰 요약을 불러오는 중입니다."/>}<section className="mt-6 overflow-hidden rounded-xl border border-[#e2e8f0] bg-white"><ReviewFilter value={input} onChange={setInput} onSearch={search} onReset={reset} disabled={loading}/>{loading ? <LoadingState className="min-h-64"/> : error ? <ErrorState title="리뷰를 불러오지 못했습니다" description={error}/> : list?.content.length ? <><div className="overflow-x-auto"><div className="min-w-[1280px]"><div className="grid h-11 grid-cols-[85px_110px_110px_120px_2.5fr_1.4fr_110px_105px_90px_145px] items-center bg-[#f8fafc] px-3 text-[11px] font-semibold text-[#94a3b8]"><span>번호</span><span>유형</span><span>회원</span><span>별점</span><span>내용</span><span>프로젝트</span><span>작성일</span><span>홍보상태</span><span>공개여부</span><span>관리</span></div>{list.content.map((r) => <ReviewRow key={r.siteReviewId} review={r} disabled={submitting} onToggleVisibility={(review) => setPending({ type: "visibility", review })} onTogglePromotion={(review) => setPending({ type: "promotion", review })}/>)}</div></div><div className="flex items-center justify-between px-5 py-4 text-[13px]"><span>총 {list.totalElements}개 · {list.page + 1}/{Math.max(list.totalPages, 1)} 페이지</span><div className="flex gap-2"><button disabled={list.first} onClick={() => changePage(page - 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">이전</button><button disabled={list.last} onClick={() => changePage(page + 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">다음</button></div></div></> : <div className="py-16 text-center text-[#64748b]">조건에 맞는 리뷰가 없습니다.</div>}</section><ConfirmModal open={pending !== null} title="리뷰 설정을 변경할까요?" description={pending ? <>{pending.review.siteReviewNo} 리뷰를 &apos;{actionLabel}&apos; 상태로 변경합니다.{actionError ? <span className="mt-2 block text-red-600">{actionError}</span> : null}</> : undefined} confirmText={submitting ? "처리 중..." : "변경"} cancelText="취소" onConfirm={() => { if (!submitting) void confirm(); }} onClose={() => { if (!submitting) { setPending(null); setActionError(undefined); } }} closeOnOverlayClick={false}/></div>;
}
